"""
YouTube Data API v3 publisher.

Requirements:
  1. Google Cloud project with YouTube Data API v3 enabled
  2. OAuth 2.0 Client ID (Desktop app) → download client_secrets.json
  3. Run scripts/auth_youtube.py ONCE on the host to generate the token
  4. Place both files in ./data/credentials/:
       data/credentials/youtube_client_secrets.json
       data/credentials/youtube_token.json          ← generated by auth script

Env vars:
  YOUTUBE_ENABLED=true
  YOUTUBE_PRIVACY=public   (public | unlisted | private)
  YOUTUBE_CATEGORY_ID=27   (27=Education, 22=People, 25=News)
  YOUTUBE_MADE_FOR_KIDS=false
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

logger = logging.getLogger(__name__)

DATA_ROOT        = Path(os.environ.get("DATA_ROOT", "/data"))
CREDENTIALS_DIR  = DATA_ROOT / "credentials"
TOKEN_FILE       = CREDENTIALS_DIR / "youtube_token.json"
SECRETS_FILE     = CREDENTIALS_DIR / "youtube_client_secrets.json"

YOUTUBE_SCOPES   = ["https://www.googleapis.com/auth/youtube.upload"]
PRIVACY          = os.getenv("YOUTUBE_PRIVACY", "public")
CATEGORY_ID      = os.getenv("YOUTUBE_CATEGORY_ID", "27")      # Education
MADE_FOR_KIDS    = os.getenv("YOUTUBE_MADE_FOR_KIDS", "false").lower() == "true"
CHUNK_SIZE       = 5 * 1024 * 1024    # 5 MB resumable upload chunk


class YouTubePublisher:
    platform_name = "youtube"

    def _get_credentials(self):
        from google.oauth2.credentials import Credentials
        from google.auth.transport.requests import Request

        if not TOKEN_FILE.exists():
            raise FileNotFoundError(
                f"YouTube token not found at {TOKEN_FILE}. "
                "Run 'python scripts/auth_youtube.py' on the host first."
            )

        creds = Credentials.from_authorized_user_file(str(TOKEN_FILE), YOUTUBE_SCOPES)

        if creds.expired and creds.refresh_token:
            logger.info("Refreshing YouTube OAuth token…")
            creds.refresh(Request())
            TOKEN_FILE.write_text(creds.to_json())
            logger.info("YouTube token refreshed and saved.")

        if not creds.valid:
            raise RuntimeError(
                "YouTube credentials are invalid and could not be refreshed. "
                "Run 'python scripts/auth_youtube.py' again."
            )
        return creds

    def publish(
        self,
        video_path: Path,
        title: str,
        caption: str,
        hashtags: list[str],
        job: dict,
    ) -> dict:
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload

        creds = self._get_credentials()
        youtube = build("youtube", "v3", credentials=creds, cache_discovery=False)

        tags = [h.lstrip("#") for h in hashtags[:500]]   # max 500 chars combined

        description = (
            f"{caption[:4500]}\n\n"
            f"{' '.join(hashtags[:20])}\n\n"
            f"⚠️  {job.get('extra_params', {}).get('disclaimer', 'This video is for educational purposes only.')}"
        )

        body = {
            "snippet": {
                "title":                title[:100],
                "description":          description[:5000],
                "tags":                 tags,
                "categoryId":           CATEGORY_ID,
                "defaultLanguage":      "en",
                "defaultAudioLanguage": "en",
            },
            "status": {
                "privacyStatus":           PRIVACY,
                "selfDeclaredMadeForKids": MADE_FOR_KIDS,
            },
        }

        media = MediaFileUpload(
            str(video_path),
            mimetype="video/mp4",
            resumable=True,
            chunksize=CHUNK_SIZE,
        )

        request = youtube.videos().insert(
            part="snippet,status",
            body=body,
            media_body=media,
        )

        logger.info("Uploading to YouTube (file: %s, size: %.1f MB)…",
                    video_path.name, video_path.stat().st_size / 1024 / 1024)

        response = None
        while response is None:
            status, response = request.next_chunk()
            if status:
                pct = int(status.progress() * 100)
                logger.info("YouTube upload progress: %d%%", pct)

        video_id  = response["id"]
        video_url = f"https://www.youtube.com/watch?v={video_id}"
        logger.info("YouTube upload complete: %s", video_url)

        return {
            "platform":         "youtube",
            "status":           "SUCCESS",
            "platform_post_id": video_id,
            "platform_url":     video_url,
        }
